name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 11.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish SGREDecryptor --configuration Release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SGREDecryptor
        path: SGREDecryptor/bin/Release/net11.0/publish
